### ISSUE TITLE
Images get resized to the maximum width/height if I edit the field in which they exist.

### ISSUE THREAD

**Issue by alih1029** [Arthur-Milchior/anki-resize-image#2]
Prior to editing field, where I add text — https://imgur.com/yohmnic

Editing Field — https://i.imgur.com/fW62Xt0.png

Afterwards — https://i.imgur.com/kyMhDMR.png

**Comment by Arthur-Milchior** [comment]
I'm sorry, but I absolutely don't understand what those images are supposed to show me. The second image is not even the same picture.
Can you please tell me anki version, OS, and which other add-on you have ? You're the firs to signal this problem, so I suspect there is some strange interaction.
Can you also tell me whether you did update the add-on today ? I want to be sure it's the actual version

**Comment by alih1029** [comment]
So in Image 1, is the card Unedited.

In Image 2, I edit the card, and in the field where there are prior images, even adding/deleting text, automatically resizes the images in that field to the minimum height/width per the config file for the addon.

Image 3, shows the result of adding "TEST" and shows that all the images are resized to the minimum width/height setting.

**Comment by Arthur-Milchior** [comment]
Ouch. Quite a lot of add-on. It's going to be hard to find the interaction.
There are too many add-ons to check all of them manually for me. Can I ask you to disable all of them and try resize alone. If it doesn't work, I'll know I don't have to look at all add-ons and only at your os/anki version/config. Otherwise, I'll need to find which add-on creates the problem.

If the problem is due to another add-on, can you use dichotomy to find which add-on is incompatible. That is, disable only half the add-on. If it still break, disable half of the enabled add-ons. And so on until it works again. Then it means the incompatible add-on is one of the add-on disabled recently. You can do this until you found only the very add-on creating the problem. Then I can try to make them compatible.

**Comment by alih1029** [comment]
So I went through each addon individually, and apparently the one that creates the issue is the Hoochie Papa Randomize New Cards addon.

**Comment by Arthur-Milchior** [comment]
I'm sorry for you, going individually probably takes a lot of time.
I'm going to take a look at it. I never used the Hoochie family. 
I can't start to imagine how they are interfering, I would never have guessed it, they seems so unrelated

**Comment by Arthur-Milchior** [comment]
You mean [HoochiePapa: Randomize New Queue](https://ankiweb.net/shared/info/1173108619) ?
That's not exactly the same name

**Comment by Arthur-Milchior** [comment]
I now have exactly two add-on installed: resize image and HoochiePapa: Randomize New Queue 
I don't have any issue with size of card.
Looking at the code of HoochiePapa, I can't imagine that our add-on have any interaction.
Can you please confirm that:
* if you have only my add-on enabled, and everything else disabled, my add-on works
* if you have both HoochiePapa: Randomize New Queue and my add-on enabled, and NOTHING else, my add-on breaks your image size ?

And that you changed nothing else. Not the version of anki, not the configuration of any add-on, ...

I'm sorry to ask you for this confirmation, but what you write is extremely hard to believe. After all, the Hoochie add-ons does not deal with the editor in any way

**Comment by alih1029** [comment]
[image: image.png]

Right now I have no addons active except for your addon

1. Pre editing
[image: image.png]

2. After Editing -- apparently it resized everything automatically again

[image: image.png]

**Comment by Arthur-Milchior** [comment]
The images did not load
You didn't answer about the configuration. Did you change it ? Did you keep the default one ?

**Comment by alih1029** [comment]
yes kept the default one

**Comment by alih1029** [comment]
https://imgur.com/w1byhMJ
https://imgur.com/ptX0eZy
https://imgur.com/undefined

**Comment by Arthur-Milchior** [comment]
The last link is broken.
Do you update between different message ? Because I keep updating the add-on. I corrected a bug which made the images's size to be too small. By luck I may have hoped it did correct your problem too. Even if I doubt it.

When you click on a field, you can press ctrl+alt+x to show its html content. Can you do it on a field with the problem, and paste the result here. Or better, export a card with the problem and share it.
On .20 you can export card directly from browser

**Comment by alih1029** [comment]
Whatever, you changed made it work! thank you so mucH!
