### ISSUE TITLE
Does resizing images with this addon actually impact file size?

### ISSUE THREAD

**Issue by CodingHorrors** [Arthur-Milchior/anki-resize-image#31]
Hey, thank you for your great addon!

I just wanted to know if resizing the images impacts the file size. I'm working with a lot of images and my main concern is the size of the data since I want to sync the cards between mobile and desktop. If not, I'd appreciate it if you could point me to an addon that actually makes files smaller.

Best wishes,
Alex

**Comment by Arthur-Milchior** [comment]
It does not change image, only the way they are displayed. I don't know such addon, sorry

**Comment by thiswillbeyourgithub** [comment]
@CodingHorrors there is an addon that automatically crops the image when pasting them, this allows to have consistent image size and quality. I don't remember the name.

Otherwise if you just want to reduce the size of you collection you can dive into your collection folder (mine is /home/user/.local/share/Anki2/profile_name/collection_media) and check the size there. I'm on linux so I can just use ncdu to see what is taking most of the space, you can also batch reduce their quality. As long as you don't modify the filenames anki won't notice anything.

**Comment by CodingHorrors** [comment]
> @CodingHorrors there is an addon that automatically crops the image when pasting them, this allows to have consistent image size and quality. I don't remember the name.
> 
> Otherwise if you just want to reduce the size of you collection you can dive into your collection folder (mine is /home/user/.local/share/Anki2/profile_name/collection_media) and check the size there. I'm on linux so I can just use ncdu to see what is taking most of the space, you can also batch reduce their quality. As long as you don't modify the filenames anki won't notice anything.

Cheers, thanks a lot! This is very useful information.
