### ISSUE TITLE
Question: Will gif size editing be supported in future?

### ISSUE THREAD

**Issue by Iris3Meow** [Arthur-Milchior/anki-resize-image#6]

**Comment by Arthur-Milchior** [comment]
I just tested on this random gif https://ressources.blogdumoderateur.com/2013/02/gif-anime.gif and it works perfectly.
Please do exactly the same thing with a gif and a non-gif image and tell me what are the differences for you

**Comment by Iris3Meow** [comment]
The gif you linked works as intended.
However, this one doesn't work
https://gph.is/g/ZYmqAwp

**Comment by Arthur-Milchior** [comment]
You linked to a webpage and not a gif. There are a ton of things on the page. Can you please give me just the gif ?

**Comment by Iris3Meow** [comment]
How about this link?
https://media.giphy.com/media/Ifh0I89dL5eRxKBEZp/giphy.gif

**Comment by Arthur-Milchior** [comment]
I tested it and it when I open the previewer, it works as well as anything else.
Can you please tell me whether you did "do exactly the same thing with a gif and a non-gif image" ? Because you told me what was the problem, but I don't know whether you tested the same way any other image and whether they were any difference.
There should be no reason for the problem to be due to the fact that it's gif and not another format
