### ISSUE TITLE
Aspect ratio not preserved on Ankidroid on resized images.

### ISSUE THREAD

**Issue by ExtremeCoolDude** [Arthur-Milchior/anki-resize-image#9]
Have this weird problem, when resized images appear like this on ankidroid :

![Screenshot_20200305-173648_AnkiDroid (1)](https://user-images.githubusercontent.com/50034073/76426016-94dcc600-63d2-11ea-8ee1-85e580adc115.jpg)

  
For comparison, one image has been altered below with resizer :
![Screenshot_20200311-200337_AnkiDroid](https://user-images.githubusercontent.com/50034073/76426790-9e1a6280-63d3-11ea-8d27-d3f11bf97ccf.jpg)
 
Don't know if this can be solved via some simple css trick, or the problem lies on the add-on itself. 

Using anki 2.1.15
add-ons:
![image](https://user-images.githubusercontent.com/50034073/75095466-1d7afa00-55bd-11ea-9d93-b51313c47194.png)

**Comment by Arthur-Milchior** [comment]
Thanks for the bug report.
I'll take a look at what css uses ankidroid.
I believe that ankidroid decided not to respect the image size you have chosen and to limit the width tho the phone's width. And since height is fixed, it does not resize keeping proportion.
Would you accept to share a card with the problem with me.

You can export single card selected in Browser using https://ankiweb.net/shared/info/1983204951 or by having a more recent version of anki

That would help me since I would not have to create the problem by myself.

**Comment by ExtremeCoolDude** [comment]
[Archive.zip](https://github.com/Arthur-Milchior/anki-resize-image/files/4321873/Archive.zip)

**Comment by Arthur-Milchior** [comment]
Sorry, I totally forgot this bug report. 
If you're still interested in solving it, can you please let me know what configuration you use for this add-on.
I suspect that if you put "preserve ratio while resizing" to "original" and then resize the image, the problem will be solved. Because in buganki, both width and size are set and it may be the reason of the problem

**Comment by ExtremeCoolDude** [comment]
Hi Arthur, tbh I stopped checking github after a while, and just sucked it up, and preferred desktop Anki whenever possible.  I've since started using Anki 2.1.23.  I did a trial right now, and the issue isn't there! Images seem to be appearing normal!


![image](https://user-images.githubusercontent.com/50034073/80132438-63533f00-85bb-11ea-989e-763daf347d60.png)

**Comment by Arthur-Milchior** [comment]
Great.

The good news about update is that it applies to everyone

**Comment by ExtremeCoolDude** [comment]
Thank you!
